### ISSUE TITLE
스켈레톤 UI 구현

### ISSUE THREAD

**Issue by task11** [7th-wanted-pre-onboarding-frontend/pre-onboarding-7th-2-2-1#7]
```css
.skeleton {
  background-color: #e0e3e3;
  position: relative;
  overflow: hidden;
}

.skeleton::after {
  content: '';
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  background: linear-gradient(
    90deg,
    rgba(255, 255, 255, 0),
    rgba(255, 255, 255, 0.2) 20%,
    rgba(255, 255, 255, 0.5) 60%,
    rgba(255, 255, 255, 0)
  );
  transform: translateX(-100%);
  animation: shimmer 2s infinite;
}

@keyframes shimmer {
  100% {
    transform: translateX(100%);
  }
}
```
